<?php
	$index_path="index.php";
	$footer_path="header_footer/footer.php";
	$header_path="header_footer/header.php";
	$css_default_path="default.css";
	$add_product_path="add.php";
	$register_path="register.php";
	$paths_path="paths/paths.php";
	$reg_errors_path="registration_errors.php";
	$logout_path="logout.php";
	$login_path="login.php";
?>